
steps:
  # 1. Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genai-app-backend', '-f', 'backend/Dockerfile.prod', 'backend']

  # 2. Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genai-app-backend']

  # 3. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'genai-app-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/genai-app-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Or secure it if you want
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID'

  # 4. Build Frontend Image
  # We need the backend URL to bake into the frontend if we were doing SSG/ISR revalidation that depended on it,
  # but our proxy is runtime-based via process.env.BACKEND_URL. 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genai-app-frontend', '-f', 'Dockerfile.prod', '.']

  # 5. Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genai-app-frontend']

  # 6. Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'genai-app-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/genai-app-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # Set BACKEND_URL to the URL of the deployed backend service
      # NOTE: We might not know the URL until after step 3. 
      # A common pattern is to deploy backend, get URL, then deploy frontend.
      # For simplicity here, we assume you might need to update this env var manually once or automate it with a script.
      # BUT, Cloud Run URLs are deterministic if you use the same service name. 
      # https://REGION-PROJECT_ID.cloudrun.app usually.
      # Let's try to fetch it dynamically or just set it to a placeholder you can update.
      # Better approach: We can use a script in Cloud Build to capture the output.
      # For now, let's just deploy and you can update the env var in the Console, or we add a step to get it.
    
images:
  - 'gcr.io/$PROJECT_ID/genai-app-backend'
  - 'gcr.io/$PROJECT_ID/genai-app-frontend'
