steps:
  # 1. Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genai-app-backend', '-f', 'backend/Dockerfile.prod', 'backend']

  # 2. Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genai-app-backend']

  # 3. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'genai-app-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/genai-app-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--service-account'
      - 'app-account@trial-project-ushikoshi.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID'
      - '--set-secrets'
      - 'LOCATION_FOR_CAR_QUIZZ=LOCATION_FOR_CAR_QUIZZ:latest,GCS_BUCKET_NAME=GCS_BUCKET_NAME:latest,INTERNAL_API_KEY=INTERNAL_API_KEY:latest,GCS_BUCKET_NAME_FOR_ENGLISH_REVIEW=GCS_BUCKET_NAME_FOR_ENGLISH_REVIEW:latest,GCS_BUCKET_NAME_FOR_CONSUL_DOC=GCS_BUCKET_NAME_FOR_CONSUL_DOC:latest,SERVICE_ACCOUNT_KEY=SERVICE_ACCOUNT_KEY:latest,YOUTUBE_PROXY=YOUTUBE_PROXY:latest,GOOGLE_CLOUD_API_KEY=GOOGLE_CLOUD_API_KEY:latest,GCS_BUCKET_KNOWLEDGE=GCS_BUCKET_KNOWLEDGE:latest,FIRESTORE_COLLECTION_KNOWLEDGE=FIRESTORE_COLLECTION_KNOWLEDGE:latest'

  # 4. Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'IS_CLOUD_RUN=true', '-t', 'gcr.io/$PROJECT_ID/genai-app-frontend', '-f', 'Dockerfile.prod', '.']

  # 5. Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genai-app-frontend']

  # 6. Deploy Frontend to Cloud Run (Dynamic BACKEND_URL)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # 1. Hardcoded Service URLs (Reliability Fix)
        echo "Using Hardcoded Service URLs..."
        BACKEND_URL="https://genai-app-backend-yg7yzstuza-uc.a.run.app"
        FRONTEND_URL="https://genai-app-frontend-yg7yzstuza-uc.a.run.app"
        
        echo "Backend URL: $$BACKEND_URL"
        echo "Frontend URL: $$FRONTEND_URL"

        # 2. Deploy Frontend
        gcloud run deploy genai-app-frontend \
          --image gcr.io/$PROJECT_ID/genai-app-frontend \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --service-account app-account@trial-project-ushikoshi.iam.gserviceaccount.com \
          --set-env-vars BACKEND_URL=$$BACKEND_URL,ALLOWED_EMAIL=haruki.u@gmail.com,NEXTAUTH_URL=$$FRONTEND_URL,IS_CLOUD_RUN=true \
          --set-secrets GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest,INTERNAL_API_KEY=INTERNAL_API_KEY:latest

  # 7. Build Office Add-in
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genai-app-office-addin', '-f', 'office-addin/Dockerfile.prod', 'office-addin']

  # 8. Push Office Add-in
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genai-app-office-addin']

  # 9. Deploy Office Add-in
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'genai-app-office-addin'
      - '--image'
      - 'gcr.io/$PROJECT_ID/genai-app-office-addin'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--service-account'
      - 'app-account@trial-project-ushikoshi.iam.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/genai-app-backend'
  - 'gcr.io/$PROJECT_ID/genai-app-frontend'
  - 'gcr.io/$PROJECT_ID/genai-app-office-addin'

options:
  logging: CLOUD_LOGGING_ONLY
