
steps:
  # 1. Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genai-app-backend', '-f', 'backend/Dockerfile.prod', 'backend']

  # 2. Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genai-app-backend']

  # 3. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'genai-app-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/genai-app-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'app-account@trial-project-ushikoshi.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID'
      - '--set-secrets'
      - 'LOCATION_FOR_CAR_QUIZZ=LOCATION_FOR_CAR_QUIZZ:latest,GCS_BUCKET_NAME=GCS_BUCKET_NAME:latest'

  # 4. Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genai-app-frontend', '-f', 'Dockerfile.prod', '.']

  # 5. Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genai-app-frontend']

  # 6. Deploy Frontend to Cloud Run (Dynamic BACKEND_URL)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # 1. Get Backend URL
        echo "Fetching Backend URL..."
        BACKEND_URL=$$(gcloud run services describe genai-app-backend --region us-central1 --format='value(status.url)')
        echo "Backend URL: $$BACKEND_URL"

        # 2. Deploy Frontend with BACKEND_URL
        gcloud run deploy genai-app-frontend \
          --image gcr.io/$PROJECT_ID/genai-app-frontend \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --service-account app-account@trial-project-ushikoshi.iam.gserviceaccount.com \
          --set-env-vars BACKEND_URL=$$BACKEND_URL
    
images:
  - 'gcr.io/$PROJECT_ID/genai-app-backend'
  - 'gcr.io/$PROJECT_ID/genai-app-frontend'

options:
  logging: CLOUD_LOGGING_ONLY
