
steps:
  # 1. Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genai-app-backend', '-f', 'backend/Dockerfile.prod', 'backend']

  # 2. Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genai-app-backend']

  # 3. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'genai-app-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/genai-app-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'app-account@trial-project-ushikoshi.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'PROJECT_ID=$PROJECT_ID'
      - '--set-secrets'
      - 'LOCATION_FOR_CAR_QUIZZ=LOCATION_FOR_CAR_QUIZZ:latest,GCS_BUCKET_NAME=GCS_BUCKET_NAME:latest,INTERNAL_API_KEY=INTERNAL_API_KEY:latest'

  # 4. Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/genai-app-frontend', '-f', 'Dockerfile.prod', '.']

  # 5. Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/genai-app-frontend']

  # 6. Deploy Frontend to Cloud Run (Dynamic BACKEND_URL)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # 1. Hardcoded Service URLs (Reliability Fix)
        echo "Using Hardcoded Service URLs..."
        BACKEND_URL="https://genai-app-backend-yg7yzstuza-uc.a.run.app"
        FRONTEND_URL="https://genai-app-frontend-yg7yzstuza-uc.a.run.app"
        
        echo "Backend URL: $$BACKEND_URL"
        echo "Frontend URL: $$FRONTEND_URL"

        # 2. Deploy Frontend
        gcloud run deploy genai-app-frontend \
          --image gcr.io/$PROJECT_ID/genai-app-frontend \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --service-account app-account@trial-project-ushikoshi.iam.gserviceaccount.com \
          --set-env-vars BACKEND_URL=$$BACKEND_URL,ALLOWED_EMAIL=haruki.u@gmail.com,NEXTAUTH_URL=$$FRONTEND_URL,IS_CLOUD_RUN=true \
          --set-secrets GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,NEXTAUTH_SECRET=NEXTAUTH_SECRET:latest,INTERNAL_API_KEY=INTERNAL_API_KEY:latest
    
images:
  - 'gcr.io/$PROJECT_ID/genai-app-backend'
  - 'gcr.io/$PROJECT_ID/genai-app-frontend'

options:
  logging: CLOUD_LOGGING_ONLY
