const devCerts = require("office-addin-dev-certs");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const path = require("path");

module.exports = async (env, options) => {
    const dev = options.mode !== "production";
    const config = {
        devtool: "source-map",
        entry: {
            taskpane: "./src/taskpane.js",
        },
        output: {
            clean: true,
            path: path.resolve(__dirname, "dist"),
        },
        resolve: {
            extensions: [".html", ".js"],
        },
        module: {
            rules: [
                {
                    test: /\.html$/,
                    exclude: /node_modules/,
                    use: "html-loader",
                },
                {
                    test: /\.(png|jpg|jpeg|gif|ico)$/,
                    type: "asset/resource",
                    generator: {
                        filename: "assets/[name][ext][query]",
                    },
                },
            ],
        },
        plugins: [
            new HtmlWebpackPlugin({
                filename: "index.html",
                template: "./src/index.html",
                chunks: ["taskpane"],
            }),
            new CopyWebpackPlugin({
                patterns: [
                    {
                        from: "src/assets/*",
                        to: "assets/[name][ext][query]",
                    },
                    {
                        from: "src/taskpane.css",
                        to: "taskpane.css",
                    },
                    {
                        from: "manifest.xml",
                        to: "manifest.xml",
                        transform(content) {
                            if (dev) {
                                return content;
                            } else {
                                return content;
                            }
                        },
                    },
                ],
            }),
        ],
        devServer: {
            static: {
                directory: path.join(__dirname, "dist"),
            },
            headers: {
                "Access-Control-Allow-Origin": "*",
            },
            server: {
                type: "https",
                options: await getHttpsOptions(),
            },
            port: 3000,
            host: '0.0.0.0', // Important for Docker
            allowedHosts: "all",
            client: {
                webSocketURL: 'auto://0.0.0.0:0/ws',
            },
        },
    };

    return config;
};

const fs = require('fs');

async function getHttpsOptions() {
    const homedir = require('os').homedir();
    const certPath = path.resolve(homedir, '.office-addin-dev-certs');

    // Ensure the folder exists
    if (!fs.existsSync(certPath)) {
        fs.mkdirSync(certPath, { recursive: true });
    }

    // Check if certs exist, if not generate them manually or use dummy self-signed
    // For container simplicity, we will assume the dockerfile generated them OR we generate simple ones here without 'installing'
    // But better yet, let's use the standard devCerts.getHttpsServerOptions BUT mocking the install behavior?
    // Actually, devCerts has no option to skip install.
    // So we will just point to the files generated by `office-addin-dev-certs install` if they exist.

    try {
        const options = await devCerts.getHttpsServerOptions();
        return options;
    } catch (e) {
        console.warn("Auto-cert generation failed (likely due to sudo). Falling back to manual check.");
        // If it failed, it might have still generated the files but failed to 'install' trust.
        // Let's try to read them directly if they match default locations.
        const keyPath = path.join(certPath, 'localhost.key');
        const crtPath = path.join(certPath, 'localhost.crt');
        const caPath = path.join(certPath, 'ca.crt');

        if (fs.existsSync(keyPath) && fs.existsSync(crtPath)) {
            return {
                key: fs.readFileSync(keyPath),
                cert: fs.readFileSync(crtPath),
                ca: fs.existsSync(caPath) ? fs.readFileSync(caPath) : undefined
            };
        }
        throw e;
    }
}
